server:
  port: 9001

application:
  name: UserService
  id: 0

kafka:
  bootstrapAddress: localhost:9092
  group:
    id: 0

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/UserServiceDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update